branch-defaults:
  master:
    environment: BodieWebDesign-dev
global:
  application_name: Bodie Web Design
  default_ec2_keyname: adam.bodie.key757063
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
